diff --git a/Cargo.toml b/Cargo.toml
index 07c308e1..d4ef2f1d 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -128,3 +128,7 @@ opt-level = 1
 strip = "none"
 debug = false
 incremental = false
+
+[patch.crates-io]
+ort = { git = "https://github.com/pykeio/ort", branch = "main" }
+
